version: '3'

services:
  node:
    build: .
    entrypoint: /usr/local/bin/nodeos
    command: --data-dir /telos/data --config-dir /telos/data --genesis-json genesis.json
    restart: on-failure
    ports:
      - "8888:8888"
      - "9876:9876"
    volumes:
      - ./volumes/data:/telos/data
      - ./config.ini:/telos/data/config.ini:ro
      - ./genesis.json:/telos/data/genesis.json:ro

#  mongo:
#    image: mongo:4
#    restart: on-failure
#    environment:
#      MONGO_INITDB_DATABASE: telos
#    volumes:
#      - ./volumes/db:/data/db
